### ISSUE TITLE
KNX - Installation du Gateway USB-KNX dans une VM

### ISSUE THREAD

**Issue by al31h** [al31h/pvedomo#3]
Objectif: Avoir un gateway KNX dans une VM, pour que Home Assistant soit indépendant de la solution de couplage au bus KNX.

Principe: Démon KNXD installé sur uen VM Debian minimale, qui est configuré comme serveur de tunnelling KNX

**Installation de la VM**

- Création d'une VM Debian dans Proxmox, avec 8Gb de disque, 256 Mo de RAM, 1 CPU/1 coeur, client QEMU installé pour l'interface réseau
- Ajout du périphérique USB avec code frabricant/produit : 0e77/0104 (interface kNX USB d'EibMarket)

![image](https://user-images.githubusercontent.com/10150677/103273455-a4f47f00-49bf-11eb-9f26-123c730653d2.png)

- Installation de Debian 10.7.0 i386 en version non graphique, avec uniquement le serveur SSH en service de base

**Installation et configuration KNXD**

- Installation du package knxd depuis les dépôts debian (source: https://github.com/knxd/knxd)

```
apt update
apt install knxd
```
- Configuration du démon dans /etc/knxd.conf (source: https://github.com/knxd/knxd/issues/366)

`KNXD_OPTS="--eibaddr=0.1.1 --client-addrs=0.1.2:8 -DT --Server=:3671 --listen-local=/tmp/knxd -B log -b usb:"
`

**Comment by al31h** [comment]
**Test avec Home Assistant**

Dans le fichier de configuration configruation.yaml

```
knx:
  tunneling:
    host: '10.10.10.74'
    port: 3671
    local_ip: '10.10.10.73'
  light:
    - name: 'Chambre 5 plafond'
      address: '1/1/112'
      state_address: '1/4/112'
    - name: 'Bureau 1'
      address: '1/1/109'
      state_address: '1/4/109'
    - name: 'Bureau 2'
      address: '1/1/121'
      state_address: '1/4/121'
```

Test OK.
